
# ALIASES TO USE FOR DEVELOPMENT

# Generally useful
alias aliases='cat ~/.bash_aliases'
alias etsin_src='cd {{ app_base_path }}'
alias source_pyenv='source {{ python_virtualenv_path }}/bin/activate'
alias tail_app_log='tail -f -n 200 {{ app_log_base_path }}/{{ project_name }}.log'
alias tail_reindexing_log='tail -f -n 200 {{ app_log_base_path }}/reindexing.log'
# Run tests in virtual environment
alias run_flask_tests='cd {{ app_base_path }} && pytest --cov=etsin_finder tests/ && cd -'
alias runserver='cd {{ app_base_path }} && sudo {{ python_virtualenv_path }}/bin/gunicorn --bind unix:{{ nginx_gunicorn_socket_path }} --user {{ app_user }} --group nginx --access-logfile - --error-logfile - --config /etc/gunicorn.py --group nginx --reload etsin_finder.finder:app'
alias npmwatch='cd {{ app_frontend_path }} && npm run watch'
alias delete_index='{{ etsin_reindexer_path }}/scripts/delete_index.sh'
alias create_index='{{ etsin_reindexer_path }}/scripts/create_empty_index.sh'
alias load_test_data_to_index='{{ etsin_reindexer_path }}/scripts/load_test_data_to_index.sh'
